server:
  port: 5000
  #注册到eureka的服务器名称
spring:
  application:
    name: nohairLoss-server-zuul
#服务注册到eureka地址
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    nhUserapi:
      path:/nhUser/**
      serviceId:noHairLoss-eurake-user
    nhFeignapi:
      path:/ngFeign/**
      serviceId:nohairLoss-feign-client
    nhRibbonapi:
      path:/ngRibbon/**
      serviceId:nohairLoss-eureka-ribbon