###服务启动端口号
server:
    port: 9913
spring:
  application:
    name: noHairLoss-eurake-user
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
