###服务端口号
server:
  port: 8761
###eureka 基本信息配置
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/
    #表示是否将当前应用注册到eureka-server上，默认为true，
    register-with-eureka: false
    #表示是否从eureka-server获取注册信息，
    fetch-registry: false
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/itripdb?useUnicode=true&amp;characterEncoding=utf-8
#    data-username: root
#    password: root
debug: true
security:
  basic:
    enabled: false
